[build]
  publish = "dist/tarteel/browser"
  command = "ng build --configuration production"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/tarteel/browser"
