[build]
  publish = "dist/tarteel/browser"
  command = "npm ci && npm run build:production"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "api/endpoints"
  node_bundler = "esbuild"   
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200